version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
    allow:
      - dependency-name: "com.solace.*"
      - dependency-name: "com.solacesystems:*"
      - dependency-name: "org.springframework.*"
      - dependency-name: "io.pivotal.cfenv:*"
      - dependency-name: "org.apache.logging.log4j:*"
